/*
 * Copyright (c) 2026, Danilo Pianini, Nicolas Farabegoli, Elisa Tronetti,
 * and all authors listed in the `build.gradle.kts` and the generated `pom.xml` file.
 *
 * This file is part of Collektive, and is distributed under the terms of the Apache License 2.0,
 * as described in the LICENSE file in this project's repository's top directory.
 */

package it.unibo.collektive.compiler.backend.transformers

import it.unibo.collektive.compiler.backend.util.StackFunctionCall
import org.jetbrains.kotlin.ir.declarations.IrFunction

/**
 * Traversal state for [AlignmentTransformer].
 *
 * [functionCallStack] tracks the semantic nesting used to build stable alignment tokens.
 * [currentFunctionScope] tracks the IR declaration that must own any temporary variables
 * generated by the alignment transformer.
 *
 * These two pieces of state deliberately stay separate. Alignment tokens may be reset when
 * descending into a lambda argument, because the lambda has its own token path. The IR builder
 * scope, however, must continue to follow the innermost [IrFunction] currently being visited.
 *
 * This matters for public inline generic primitives such as `exchange`. Their bodies can contain
 * lambdas whose IR references type parameters declared by the lambda or by the inline function
 * that owns the lambda. If the plugin creates temporary variables for an expression inside such a
 * lambda but builds them with the outer aggregate function as the scope, Kotlin/Native sees an
 * inconsistent ownership chain during IR serialization. In that situation, Native may fail to find
 * the declaration container for a type parameter, for example with:
 * `No container found for type parameter 'Shared'`.
 *
 * Keeping [currentFunctionScope] in the traversal context makes every generated alignment block
 * use the same function scope as the expression it wraps, while still preserving the original
 * top-level `functionToAlign` semantics for deciding which aggregate function
 * is being transformed.
 */
data class AlignmentTraversalContext(val functionCallStack: StackFunctionCall, val currentFunctionScope: IrFunction) {
    /**
     * Starts a fresh alignment-token stack while preserving the current IR builder scope.
     */
    fun withEmptyFunctionCallStack(): AlignmentTraversalContext = copy(functionCallStack = StackFunctionCall())

    /**
     * Moves generated IR ownership to [function] while preserving the current token stack.
     */
    fun withCurrentFunctionScope(function: IrFunction): AlignmentTraversalContext =
        copy(currentFunctionScope = function)
}
